spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: 
          credential:
            client-id: 
            client-secret: 
          login-flow: 
  
          user-flows:
            sign-up-or-sign-in: 
            
